### PR TITLE
Update Nightly job to trigger it every main push

### PR DESCRIPTION
**Pull request by mustard-mh**
‼️ This will change nightly extension version from `YYYYMMDDHH` to `YYYYMMDDHHmm`. To unblock in hour publish

@jeanp413

### CODE REVIEW

**Comment by jeanp413** [comment]
Also changing to `YYYYMMDDHHmm` will make the patch version bigger than the max 32bit signed integer could cause some error in the server, [openvsx assumes 32 bit](https://github.dev/eclipse/openvsx/blob/a874a24e85653463b8cc7697d6849ea7a64f49cb/server/src/main/java/org/eclipse/openvsx/entities/ExtensionVersion.java#L252) :see_no_evil:  not sure in MS marketplace

**Comment by jeanp413** [comment]
cc @akosyakov :point_up_2:

**Comment by jeanp413** [comment]
> When we push to master we should have confidence in it. Any commit should work in theory. If we are not sure go via the PR? I don't think ability pushing to master means we can break it.

it works, it's just some code commented for testing that slipped

> How other extensions doing it? I'm pretty sure auto publish is not uncommon.

 it's once a day not on every commit

**Comment by akosyakov** [comment]
To make the matter simpler we could publish only once a day at the time when most likely there are no changes, i.e. after JP goes to sleep :) The same way how we deploy Gitpod daily?

**Comment by jeanp413** [comment]
yeah, then should we stop deploying manually and wait for auto deploy? all this time i've always deployed both at the same time

**Comment by jeanp413** [comment]
@mustard-mh is there a way to check the released commit so we don't deploy the same commit each day if no changes are made :thinking:

**Comment by mustard-mh** [comment]
> I wonder if there's a way to check the released commit so we don't deploy the same commit each day if no changes are made or is this fine 🤔

We can create a branch for nightly and compare the commit hash like gitlens does https://github.com/gitkraken/vscode-gitlens/blob/main/.github/workflows/cd-pre.yml#L26-L27

So for nightly, it will be once a day if we have some updates automatically

> all this time i've always deployed both at the same time after a change/PR

If we release stable changes, we should have nightly release too. release should trigger them both

**Comment by akosyakov** [comment]
> We can create a branch for nightly and compare the commit hash like gitlens does https://github.com/gitkraken/vscode-gitlens/blob/main/.github/workflows/cd-pre.yml#L26-L27
> So for nightly, it will be once a day if we have some updates automatically

sounds like a plan

> If we release stable changes, we should have nightly release too. release should trigger them both

I don't think we need to couple it. Nightly means once a day as you said if there are no changes. It can be done on demand as well.

**Comment by jeanp413** [comment]
Follow up PR https://github.com/gitpod-io/gitpod-vscode-desktop/pull/64

**Pull request closed without merging**
